builders:
  generatorBuilder:
    import: "package:gsdatabase/dev/generator.dart"
    builder_factories: ["generatorBuilder"]
    build_extensions: { ".dart": ["builder.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

targets:
  $default:
    builders:
      gsdatabase|generatorBuilder:
        enabled: true
        generate_for:
          - lib/src/models/info/*
          - lib/src/models/save/*
